#Target: Dependices
#<Tab>Command

target : project.c addrecord.c deleterecord.c viewrecord.c editrecord.c fun.h
	gcc project.c addrecord.c deleterecord.c viewrecord.c editrecord.c   -o a.out

run: target
	./a.out